In [11]:
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras.layers import Input, BatchNormalization, MaxPool2D
from keras import backend as K

# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

print(x_train.shape, y_train.shape)

(60000, 28, 28) (60000,)


In [12]:
import numpy as np
np.unique(y_train)
num_classes = len(np.unique(y_train))
num_classes

10

In [13]:
x_train = x_train.reshape(x_train.shape[0], 28, 28, 1)
x_test = x_test.reshape(x_test.shape[0], 28, 28, 1)
input_shape = (28, 28, 1)

# convert class vectors to binary class matrices
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255
print('x_train shape:', x_train.shape)
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

x_train shape: (60000, 28, 28, 1)
60000 train samples
10000 test samples


In [21]:
model1 = Sequential(name='CNN')
    
model1.add(Conv2D(filters=32, kernel_size=(5,5), padding='same', activation='relu',
                input_shape=(28, 28, 1)))
model1.add(BatchNormalization())
model1.add(Conv2D(filters=32, kernel_size=(5,5), padding='same', activation='relu'))
model1.add(MaxPool2D(pool_size=(2, 2))
model1.add(Dropout(rate=.25))

model1.add(Conv2D(filters=64, kernel_size=(3,3), padding='same', activation='relu'))
model1.add(BatchNormalization())
model1.add(Conv2D(filters=64, kernel_size=(3,3), padding='same', activation='relu'))
model1.add(MaxPool2D(pool_size=(2, 2), strides=(2, 2)))  # Downscale
model1.add(Dropout(rate=.25))

model1.add(Flatten())
model1.add(Dense(256, activation='relu'))
model1.add(Dropout(rate=.5))
model1.add(Dense(10, activation='softmax'))

model1.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [23]:
hist = model1.fit(x_train, y_train, epochs=10, validation_data=(x_test, y_test), verbose=1)
print("The model has successfully trained")

model.save('mnist2.h5')
print("Saving the model as mnist.h5")

Epoch 1/10
1875/1875 [==============================] - 290s 155ms/step - loss: 0.1535 - accuracy: 0.9556 - val_loss: 0.0333 - val_accuracy: 0.9876
Epoch 2/10
1875/1875 [==============================] - 305s 163ms/step - loss: 0.0922 - accuracy: 0.9746 - val_loss: 0.0474 - val_accuracy: 0.9875
Epoch 3/10
1875/1875 [==============================] - 348s 186ms/step - loss: 0.0702 - accuracy: 0.9811 - val_loss: 0.0369 - val_accuracy: 0.9885
Epoch 4/10
1875/1875 [==============================] - 324s 173ms/step - loss: 0.0615 - accuracy: 0.9830 - val_loss: 0.0255 - val_accuracy: 0.9923
Epoch 5/10
1875/1875 [==============================] - 395s 211ms/step - loss: 0.0538 - accuracy: 0.9854 - val_loss: 0.0371 - val_accuracy: 0.9886
Epoch 6/10
1875/1875 [==============================] - 412s 220ms/step - loss: 0.0486 - accuracy: 0.9871 - val_loss: 0.0220 - val_accuracy: 0.9924
Epoch 7/10
1875/1875 [==============================] - 364s 194ms/step - loss: 0.0488 - accuracy: 0.9871 - val_

In [24]:
y_pred = model.predict(x_test)

313/313 [==============================] - 5s 13ms/step


In [25]:
y_pred

array([[0.10385791, 0.10333262, 0.09572763, ..., 0.09555325, 0.0970789 ,
        0.1017554 ],
       [0.09816667, 0.10323637, 0.09780297, ..., 0.09842905, 0.0983981 ,
        0.09654094],
       [0.10268214, 0.10445961, 0.0998617 , ..., 0.09981708, 0.1009903 ,
        0.09865734],
       ...,
       [0.1049788 , 0.1051874 , 0.1036815 , ..., 0.09364278, 0.10086976,
        0.09958662],
       [0.10462417, 0.10116775, 0.09968074, ..., 0.0928559 , 0.10015117,
        0.09555851],
       [0.10622799, 0.10002553, 0.09535766, ..., 0.09683852, 0.10706969,
        0.08991738]], dtype=float32)

In [27]:
model1.evaluate(x_test, y_test)

313/313 [==============================] - 9s 28ms/step - loss: 0.0233 - accuracy: 0.9940


[0.0232900008559227, 0.9940000176429749]

In [13]:
y_pred[0]

array([0.00629686, 0.00538881, 0.00947797, 0.01490118, 0.0210649 ,
       0.01383418, 0.00269676, 0.8692795 , 0.02510904, 0.0319509 ],
      dtype=float32)

In [15]:
np.argmax(y_pred[1])

2

In [31]:
from PIL import Image
img = Image.open('/Users/gk/Desktop/two.jpeg')
img = img.resize((28,28))
img = img.convert('L')
img = np.array(img)
img = img.reshape(1,28,28,1)
img = img/255.0
res = model.predict([img])

1/1 [==============================] - 0s 32ms/step


In [32]:
res

array([[3.0323902e-01, 9.2457354e-05, 2.5537586e-01, 5.8284387e-02,
        1.6750066e-02, 3.3490950e-01, 1.8380834e-02, 3.0303765e-03,
        9.4010914e-03, 5.3635309e-04]], dtype=float32)

In [33]:
np.argmax(res[0])

5